services:
  - type: worker
    name: daily-report-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: REMINDER_HOUR
        value: "19"
      - key: REMINDER_MINUTE
        value: "0"
      - key: ALLOW_WEEKEND_TEST
        value: "false"
      - key: SEND_TEST_ON_START
        value: "false"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVERS
        sync: false
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/reports
      sizeGB: 1
